[package]
name = "Gimp"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "22.1"
winit = "0.30"
env_logger = "0.11"
log = "0.4"
pollster = "0.3"
image = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rfd = "0.14"
